# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
    before_all do
        setup_travis
        cocoapods(repo_update: true)
    end

  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "PS4WeekReleases.xcworkspace", scheme: "PS4WeekReleases")
    upload_to_app_store
  end

    desc "Capture screenshots and send to iTunes Connect"
    lane :screenshot do
        capture_screenshots
        frame_screenshots
        upload_to_app_store(ignore_language_directory_validation: true)
    end

    desc "Runs all the tests"
        lane :test do
        run_tests(scheme: "PS4WeekReleases")
    end

    after_all do |lane|
        notification(
        subtitle: "✅ Lane '#{lane}'",
        message: "Lane '#{lane}' finished with success.",
        sound: "Beep"
        )
    end

    error do |lane, exception|
        notification(
        subtitle: "❌ Lane '#{lane}'",
        message: "#{exception.message}",
        sound: "Sosumi"
        )
    end
end
